name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make test script executable
        run: chmod +x test_gcd.sh gcd.sh

      - name: Run test
        run: ./test_gcd.sh
